on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'printing content before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'printing content after'
        run: ls
        

